name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: setup Node
      uses: actions/setup-node@v1
      
    - name: install angular and build
      run: |
        npm update
        npm install -g @angular/cli > /dev/null
        ng build --prod
      
    - name: deploy
      run: 	aws s3 sync ./dist/nr-amtcard-ui/ s3://nr-amtcard-website --delete
      
